### ISSUE TITLE
EDA not preformed on train data

### ISSUE THREAD

**Issue by roanraina** [UBC-MDS/diabetes_prediction#22]
I noticed `diabetes_eda.py` is run on the cleaned LLCP2015 data.
Should we be splitting the data into a test and train set before preforming this analysis? 
Where should this be done?

**Comment by austin-shih** [comment]
We can either put the train test split in the clean script or leave as is. Looking at the full dataset for the EDA should be ok, as long as we split it before we do the analysis. I would prefer to leave it as is, I'm pulling a sample from the whole dataset then splitting it to do the analysis.

**Comment by roanraina** [comment]
solved
