### ISSUE TITLE
bib file

### ISSUE THREAD

**Issue by florawendy19** [UBC-MDS/diabetes_prediction#23]
Do we need a separate bib file for all the resources we have used or is it okay to keep it short in the reference part of the of the README file?

**Comment by roanraina** [comment]
The assignment mentions "You are expected to have a reference section and cite at least 4 external sources (data source can be one of these citations) in addition to citing the programming languages and packages used." for task 1.5. If you are doing part 1.5 as a .Rmd file, it would make the most sense to include a .bib file and auto generate the references section in the document. However, this decision is up to you.

**Comment by roanraina** [comment]
Project uses [references.bib](https://github.com/UBC-MDS/diabetes_prediction/blob/main/doc/references.bib)
